language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-sentry.gemspec
- gem install sensu-plugins-sentry-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: gcqLB7PrgONQoYBmmo2+UKLZNzv+f0PZi+1g/nynN/tXtNHjJd39vqWTMNyFab7dSSPQCToQjmNyWao4mGbmZLUfQJGS4IMn8YZ/2MNnejS/vfG4xWG4d/tZXadjjqz4NvDnM471rsdajWZz/mSBGf0a8BHIl8DLw3fD/E+Avoo=
  gem: sensu-plugins-sentry
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-sentry
